### ISSUE TITLE
Error with HoneygainAutoClaim when using mode Jumptask.

### ISSUE THREAD

**Issue by cuongdt1994** [MrLoLf/HoneygainAutoClaim#15]
When I use the JumpTask mode, the token cannot be received automatically, and I tried with other account with HomeGain wallet, the function working normally.

Below error message after run script with have lucky pot.

Generating new Token!
Logging in to Honeygain!
Traceback (most recent call last):
  File "/root/main.py", line 423, in <module>
    main()
  File "/root/main.py", line 378, in main
    if not achievements_claim(s, header):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/main.py", line 336, in achievements_claim
    not len(achievement['progresses'][0]) > 0):
            ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by MrLoLf** [comment]
I've tried to replicate this, but I wasn't able to can you provide me more information. I've added another check that should fix the error you provided here. Can you update to the newest version and check if it's still throwing the error.

**Comment by MrLoLf** [comment]
I've added another commit this probably has fixed this issue please

**Comment by cuongdt1994** [comment]
I will try it in tomorrow and feedback again.

**Comment by cuongdt1994** [comment]
Hi @MrLoLf , this commit it's work. Thank you about that.

Started HoneygainAutoClaim!
Trying to claim None.
Trying to claim None.
Claimed 10.0 Credits.
Won today 10.0 Credits.
You currently have 5063.02 Credits.

**Comment by MrLoLf** [comment]
Great to hear this. I will close this now. Thanks for the report.
