### ISSUE TITLE
DockerFile

### ISSUE THREAD

**Issue by madereddy** [MrLoLf/HoneygainAutoClaim#17]
The current DockerFile is pulling an outdated image with multiple high CVEs,

I would recommend using a newer docker image like `python:3.13.0a2-slim` or even upgrading to Chainguards Python image which is streamlined or pinning a docker image version and then using a dependency checker to automate the updates of it.

**Comment by MrLoLf** [comment]
I will look into Chainguards Python Image on this weekend, when I have a bit more time, but this should fix the high CVE cases.

**Comment by madereddy** [comment]
Opened PR for the Chainguard Image: https://github.com/MrLoLf/HoneygainAutoClaim/pull/20
