### ISSUE TITLE
main.py errors out on start

### ISSUE THREAD

**Issue by jlegue** [MrLoLf/HoneygainAutoClaim#5]
I have taken what you have started and have updated the Dockerfile such that cron is installed and the crontab entry is automatically added to the root user's list of cron jobs. This seems to have worked but I will still need to test this as your Dockerfile currently has its command set to "CMD ["python", "main.py"]" which will have the container exit after a single execution.

The issue I am having is that the main.py file is failing at initialization of the default config file per the log below:

> 2023-06-28 13:25:09 honeygainbot-honeygainbot-1  | Started HoneygainAutoClaim!
> 2023-06-28 13:25:09 honeygainbot-honeygainbot-1  | Creating config folder!
> 2023-06-28 13:25:09 honeygainbot-honeygainbot-1  | Generating new Config!
> 2023-06-28 13:25:09 honeygainbot-honeygainbot-1  | Traceback (most recent call last):
> 2023-06-28 13:25:09 honeygainbot-honeygainbot-1  |   File "/app/HoneygainAutoClaim/main.py", line 107, in <module>
> 2023-06-28 13:25:09 honeygainbot-honeygainbot-1  |     create_config()
> 2023-06-28 13:25:09 honeygainbot-honeygainbot-1  |   File "/app/HoneygainAutoClaim/main.py", line 34, in create_config
> 2023-06-28 13:25:09 honeygainbot-honeygainbot-1  |     email: str = input("Email: ")
> 2023-06-28 13:25:09 honeygainbot-honeygainbot-1  |                  ^^^^^^^^^^^^^^^^
> 2023-06-28 13:25:09 honeygainbot-honeygainbot-1  | EOFError: EOF when reading a line

The updated Dockerfile looks like this:

> FROM python:3.11-slim-buster
> WORKDIR /app
> RUN apt-get update && apt-get install -y git cron
> RUN git clone https://github.com/MrLoLf/HoneygainAutoClaim.git
> WORKDIR /app/HoneygainAutoClaim
> RUN pip install --no-cache-dir -r requirements.txt
> RUN echo "0 8 * * * python3 /app/HoneygainAutoClaim/main.py" | crontab -
> CMD ["tail", "-f", "/dev/null"]

Note the install of cron by it being added to the apt-get for git and the addition of the cron entry as the second last line. Also note the change of the CMD to be tail -f /dev/null which allows the container to remain running.

It might be beneficial to have an example of the config file that can be edited or have that file be able to be referenced from the docker host to allow for it to be easily configured without the need of connecting to the container in a shell to then use nano.

After login to the terminal I can see that the files are in the working directory as expected and that the crontab entry is in place as expected:

![image](https://github.com/MrLoLf/HoneygainAutoClaim/assets/46759194/55e4fa02-70dc-412f-9914-b83f30f7463d)

I am not a Python guy yet, so your assistance is appreciated to understand what I may be missing and get things working.

**Comment by jlegue** [comment]
I have tried to run it initially to have the file be created by adding the following line into the Dockerfile:

RUN python3 /app/HoneygainAutoClaim/main.py

This, I had hoped, would be a successful first-time run, but unfortunately, it fails with the same error mentioned previously because the container is not interactive when built.

The next attempt was from the available shell considering the docker container is now running with the tail -f as its entry command. From the shell, it is possible to fun the main.py script and enter in the user/password for HoneyGain thereby creating the config and token files that can be used to successfully run the script in the container going forward.

I did decide to make it slightly more robust by taking a copy of the config and token files into a Config folder in the Dockerfile folder that I can then edit as needed for a new user and have be copied to the container during the build process removing the need to manually run the script after a rebuild to recreate these files.

**Comment by jlegue** [comment]
Let me know if you think there is value to updating the project to include these adjustments and documenting them.

**Comment by MrLoLf** [comment]
The -f command looks interesting could you provide the line you used to run it? 

How would you do the more robust part for all users. They probably shouldn't have your credentials and token when publishing it. could you create a merge request? So I can have a look at the changes.

Thanks for your efforts.
