### ISSUE TITLE
Windows Task not working

### ISSUE THREAD

**Issue by NUCL3ARN30N** [MrLoLf/HoneygainAutoClaim#6]
Hi,
in your installation Guideline you are describing that the script must be added unter Program/Script.
However you have to set under Program/Script the path to your python installation (find it with the console "where python")
Next you must add main.py under "Add arguments (optional)" box and the local path to your folder (where main.py is located) in the "Start in (optional)" box. 

Only then is the script launching.

**Comment by MrLoLf** [comment]
I hope this description is clearer on what to do. 👍🏻
