### ISSUE TITLE
Why are we not using GitHub Actions instead of Docker?

### ISSUE THREAD

**Issue by gorouflex** [MrLoLf/HoneygainAutoClaim#8]
Here is my repo that replace docker to GitHub Actions: https://github.com/gorouflex/HoneygainPot

**Comment by gorouflex** [comment]
I have created two workflows, the `Daily` workflow will automatically run at 2pm UTC (which is 9pm in UTC+7) and there is also a manual trigger workflow

**Comment by MrLoLf** [comment]
I wasn't aware of them for this use case. Can you create a pull request with the needed changes. I would appreciate your help. But I would like to still use Docker and a local install for users that don't want it to be hosted on GitHub, so they can still self host it. I think you need to just edit the README right?

Thanks for your information. I hope to see your PR soon.

**Comment by gorouflex** [comment]
ok… i think I’ll test this formore, if I can, i think i can create a PR so that we have two options: run on GitHub Actions or Docker

**Comment by MrLoLf** [comment]
Sounds great! Thanks for your efforts.

**Comment by gorouflex** [comment]
@MrLoLf #9

**Comment by MrLoLf** [comment]
Added with #9
