### ISSUE TITLE
Remove GitHub Actions

### ISSUE THREAD

**Issue by gorouflex** [MrLoLf/HoneygainAutoClaim#95]
It's better to remove GitHub Actions from now, otherwise you'll get suspended by GitHub
Is violated to their TOS as i know, i just got suspended

**Comment by gorouflex** [comment]
@MrLoLf

**Comment by MrLoLf** [comment]
Firstly, thanks for your warning. But why should GitHub suspend me, for what exactly? Too much bandwidth use? Except for that, I don't see any reason, that might interfere with the TOS.

**Comment by gorouflex** [comment]
> Firstly, thanks for your warning. But why should GitHub suspend me, for what exactly? Too much bandwidth use? Except for that, I don't see any reason, that might interfere with the TOS.

@MrLoLf 
```

In particular, any repositories that use GitHub Actions solely to interact with 3rd party websites, to engage in incentivized activities, or for general computing purposes may fall foul of the GitHub Additional Product Terms:
 
https://docs.github.com/github/site-policy/github-terms-for-additional-products-and-features#actions
```

**Comment by MrLoLf** [comment]
Okay, so I'll just have to change my daily.yml and I should be fine. I can simply add this in my README.md, as description on what to change and then people can still use the manual as daily one. As I then don't run any GitHub Actions any longer, to do such things, but others can run them if they want to.

**Comment by MrLoLf** [comment]
I'll close this now. It should be fixed, as I deleted the .yml files running the main.py and added a new instruction for users that still want to use GitHub actions, alongside a new Disclaimer for it.
